lib/java_buildpack/container/tomcat/tomcat_gemfire_store.rb, spec/java_buildpack/container/tomcat/tomcat_gemfire_store_spec.rb
The GemFire session replication code should not fire during the
release phase unless a properly configered GemFire service is bound
to the application. If it does it causes application deployment to
fail, this commit fixes this bug.
[#86291128]
=> BugFix for the GemFire session_replication support

lib/java_buildpack/buildpack_version.rb
Refactor buildpack_version.rb to use native windows path separators
and tools (where instead of which) when in Windows to allow git hashes
to be added to output zip. Same as pull request 117 but rebased.
Issue: 117
=> Allow native Windows build support

config/spring_boot_cli.yml
This commit updates the version of Spring Boot CLI to be used
from 1.1.+ to 1.+
[#87191758]
=> Update Spring Boot CLI to version 1.+

docs/extending.md
Reverts cloudfoundry/java-buildpack#147
Previous pull request accepted without CLI in place. My appologies.
=> Revert "Update extending.md"

lib/java_buildpack/container/tomcat/tomcat_gemfire_store.rb, spec/fixtures/container_tomcat_gemfire_store_context_after.xml
Enabling local cache could cause inconsistencies in state between multiple instances of an application
Addresses issue #152
Signed-off-by: Swapnil Bawaskar <sbawaskar@pivotal.io>
=> Set enableLocalCache to false to ensure consistency of state

config/app_dynamics_agent.yml, docs/framework-app_dynamics_agent.md, lib/java_buildpack/framework/app_dynamics_agent.rb, spec/java_buildpack/framework/app_dynamics_agent_spec.rb
This commit makes it possible to supply values for the AppDynamics
application and node names in the configuration and through service
credentials. Testing and documentation also updated.
[#89413382]
=> Configurable AppDynamics application & node names

README.md, config/app_dynamics_agent.yml, config/open_jdk_jre.yml, docs/framework-app_dynamics_agent.md, lib/java_buildpack/framework/app_dynamics_agent.rb, lib/java_buildpack/jre/open_jdk_like.rb, lib/java_buildpack/util/configuration_utils.rb, spec/java_buildpack/framework/app_dynamics_agent_spec.rb, spec/java_buildpack/jre/open_jdk_jre_spec.rb, spec/java_buildpack/util/configuration_utils_spec.rb
This commit adds support for overriding buildpack configuration with
environment variables. The way Java config is processed has been
modified to allow this new support to work when configuring the
required version of Java. Includes new tests and documentation, see
the main README.md for more details.
[#86997400]
=> User configuration via variables

README.md, docs/example-embedded-web-server.md
The other buildpack examples don't make clear how to make use of the  environment variable in order to include a web server / servlet container within the application. This example does that through showing how using Jetty as an embedded container works using Cloud Foundry
=> Embedded Jetty example.

spec/bin/compile_spec.rb
Latest version of the memory calculator requires -totMemory option > 0
This is intended to fix the CI bug I'm noticing on #187
=> Add memory_limit context to compile tests

README.md
JRE version is now wrapped in a 'jre' element, and the memory_heuristics is
now wrapped in a 'memory_calculator' element.
Issue: 191
=> Corrected JVM configuration example

docs/framework-dyna_trace_agent.md
The resource section seems to be copied from another framework:
- fix naming
- remove profile example since it does not apply to dynatrace
=> Fixed resources section of dynatrace documentation

docs/jre-oracle_jre.md
as discussed in #196, the documentation about the JCE installation should be enhanced for the 'server jre'
=> document local_policy.jar location for 'server jre'

lib/java_buildpack/container/tomcat/tomcat_instance.rb
Hi,
In TomEE BP, the TomEE Instance inherits Tomcat Instance [1].
When one invokes "cf push -b https://github.com/cloudfoundry-community/tomee-buildpack"
The following will appear in the command line:
-----> Downloading Tomee Instance 1.7.2 from https://download.run.pivotal.io/tomee/tomee-1.7.2.tar.gz
Expanding Tomcat to .java-buildpack/tomee
As you can see there is "Expanding Tomcat" which is not correct when using TomEE BP.
With this change I would like to change the log statement in Java BP in a way that even when inherited Tomcat Instance will print the correct name i.e.:
-----> Downloading Tomee Instance 1.7.2 from https://download.run.pivotal.io/tomee/tomee-1.7.2.tar.gz
Expanding Tomee Instance to .java-buildpack/tomee
What do you think?
Regards,
Violeta
[1] …
=> Fixed log statement when expanding Tomcat.

docs/framework-dyna_trace_agent.md, docs/framework-ruxit_agent.md, lib/java_buildpack/framework/dyna_trace_agent.rb, lib/java_buildpack/framework/ruxit_agent.rb, spec/java_buildpack/framework/dyna_trace_agent_spec.rb, spec/java_buildpack/framework/ruxit_agent_spec.rb
Update criteria for detection of dynatrace/ruxit extensions.
=> Update dynatrace detection criteria

config/jrebel_agent.yml, lib/java_buildpack/framework/jrebel_agent.rb, spec/java_buildpack/framework/jrebel_agent_spec.rb
Use the 7.x release which has logging enabled by default, so no need to explictly set it. Also 'lib/jrebel.jar' doesn't exist anymore so removed it from the expectations.
=> Update the JRebel framework.

config/luna_security_provider.yml, docs/framework-luna_security_provider.md, lib/java_buildpack/framework/luna_security_provider.rb, spec/fixtures/framework_luna_security_provider/Chrystoki.conf, spec/fixtures/framework_luna_security_provider_logging/Chrystoki.conf, spec/java_buildpack/framework/luna_security_provider_spec.rb
* Adding support for HA logging.
* Adding HASynchronize section for HA groups.
* Fixing reconnect attempts option and changing to max retries.
=> Improvements for HA for the Luna Security Provider.

README.md
The example tells the buildpack to use version 11, not version 7.
=> Fix README to talk about correct Java version

config/new_relic_agent.yml
This change loosens the New Relic Agent version wildcard to "latest" for even major releases.
[resolves #827]
=> New Relic Agent Version

config/your_kit_profiler.yml
This change relaxes the YourKit version to select the latest available at all times rather than being tied to a given year.
=> Relax YourKit Version

config/riverbed_appinternals_agent.yml
The buildpack should use 11.7.1 by default now. -Scott
=> APMDEV-4870: Update to use the latest version of the profiler.

lib/java_buildpack/framework/app_dynamics_agent.rb, spec/java_buildpack/framework/app_dynamics_agent_spec.rb
Otherwise the following service instance:
```shell
cf cups appdynamics -p '{"account-name":"XXXX",...,"application-name":"app: foo"}'
```
will result in the application failing to start with the following error:
> 2020-11-11T15:30:25.99+0000 [APP/PROC/WEB/0] ERR Error: Could not find or load main class foo
=> Support appdynamics application names with spaces

lib/java_buildpack/framework/app_dynamics_agent.rb, spec/java_buildpack/framework/app_dynamics_agent_spec.rb
Without the change in this PR, setting `APPD_CONF_HTTP_URL` to an HTTPS URI results in the following error in the logs:
> 2020-11-11T17:10:19.47+0000 [STG/0] ERR [AppDynamicsAgent] INFO  Could not retrieve https://appdynamics-configuration.cfapps.pcfeagledev.cf-app.com/java/app-agent-config.xml. Code: 400 Message: Bad Request
=> Allow custom configuration to be fetched over HTTPS

config/tomcat.yml
We would like to update the Geode store version that the Java buildpack pulls in to an earlier version so that it is compatible with more versions of TGF4VMs.
=> Update geode store version

lib/java_buildpack/framework/app_dynamics_agent.rb, spec/java_buildpack/framework/app_dynamics_agent_spec.rb
Currently, if you attempt to fetch App Dynamics configuration from a remote server using `APPD_CONF_HTTP_URL`, it will work so long as the server is not protected with basic auth.
Downloads from the remote server are OK, but this [call to check_if_resource_exists](https://github.com/cloudfoundry/java-buildpack/blob/main/lib/java_buildpack/framework/app_dynamics_agent.rb#L146) doesn't use the standard download code and makes a direct HEAD request which doesn't currently support basic auth.
This patch uses basic auth for the HEAD request, which should allow it to support App Dynamics config from a remote server protected with basic auth.
=> Add basic auth support when using APPD_CONF_HTTP_URL to fetch configuration from a remote server.

lib/java_buildpack/framework/introscope_agent.rb
Updated Introscope Agent to use neo mode by default. The neo mode helps to improve the App startup time when using with Introscope Agent.
=> Updated Introscope Agent to use neo mode by default. 

config/introscope_agent.yml
Broadcom is migrating CA APM agents from Bintray to JFrog. Bintray will be discontinued May 1 2021
Signed-off-by: Emily Casey <ecasey@vmware.com>
=> Update CA APM artifact location

ci/Dockerfile
Still defaults to ubuntu:bionic.
=> Allow Dockerfile users to set the base image with a build arg

README.md, rakelib/dependency_cache_task.rb
As described in this [issue](https://github.com/cloudfoundry/java-buildpack/issues/848) we are using the offline package of the Java Buildpack and have the problem that we need to bundle more than one JRE with it. We can't uncomment more than one JRE in the components.yml file and a download on deployment is not possible (disabled and no network anyway). We have a little hack in place that additionally bundles SapMachine JRE so our customers can select it if they wish. However, we would prefer a more elegant solution.
I've made a tiny change that reads ADD_TO_CACHE during the bundling process and adds components to the offline cache that are not specified in components.yml
=> Allow for additional components (JREs) in the cache

config/components.yml, config/datadog_javaagent.yml, docs/framework-datadog_javaagent.md, lib/java_buildpack/framework/datadog_javaagent.rb, rakelib/versions_task.rb, spec/java_buildpack/framework/datadog_javaagent_spec.rb
Support for activating Datadog APM auto instrumentation.
The [Datadog Trace Agent](https://github.com/DataDog/datadog-cloudfoundry-buildpack) is not configured as a service binding, so we rely on detecting environment variable config for activation.
Closes #826
=> Add support for Datadog APM Javaagent

config/app_dynamics_agent.yml, docs/framework-app_dynamics_agent.md, lib/java_buildpack/framework/app_dynamics_agent.rb, spec/java_buildpack/framework/app_dynamics_agent_spec.rb
PR #837 can result in double escaping of application names when the default value is used. This is because the value gets escaped at runtime when it's selected, so it's not necessary to escape it at build time also.
It also only handles spaces. If there were a `"` in the name, that would cause an error.
--------
This PR will ensure that values for the app name that are selected during build time by the buildpack are escaped at build time and that values that are pulled at runtime before an app starts are escaped at that point in time, but not both. That way we avoid double escaping values.
In addition, it uses `Shellwords.escape` to escape the values not just surrounding them in double-quotes. This will result in properly shell escaping double quotes also.
Resolves #871
=> Adjust the way arguments are being escaped. 

lib/java_buildpack/framework/app_dynamics_agent.rb
PR #870 reversed the logic overriding the default_unique_host_name with
the application_name.  This results in problems with AppDynamics where
applications running on multiple foundations are unable to add metrics
when using the same application name in Cloud Foundry.
Really, application_name should never be used. unique_host_name is
by definition a unique identifier vs an application_name, which is not
guaranteed to be unique.
But this restores the previous logic, which was functional and may have
handled cases I am not aware of.
=> Restore unique_host_name logic for AppDynamics

lib/java_buildpack/framework/datadog_javaagent.rb, spec/java_buildpack/framework/datadog_javaagent_spec.rb
Checks for the DataDog to be installed into either `$HOME/.datadog` (new) or `$HOME/datadog` (old) locations.
Resolves #897
=> Ensures compatibility with older and newer DataDog buildpacks.

lib/java_buildpack/framework/dynatrace_one_agent.rb
Little fix in the case for the `networkzone` query parameter.
The z is now an uppercase Z :-)
=> fixed case in networkzone query parameter

config/jprofiler_profiler.yml
- Version bump was requeste by users
- Version 11.x has been EOL'd
- Version 11 is still on the downloads server. If you need to stick with 11.x, you may set `JBP_CONFIG_JPROFILER_PROFILER_VERSION` to `11.+`.
Resolves #914
=> Bump JProfiler to 12.x branch

config/tomcat.yml
Updating the default geode-store version to reflect the recommended minimum version of the product.
=> Update default geode-store version to 1.13.4

spec/java_buildpack/framework/dynatrace_one_agent_spec.rb
This PR caused a test failure, this PR fixes it.
https://github.com/cloudfoundry/java-buildpack/pull/915
=> Fixes test failure from #915

lib/java_buildpack/framework/luna_security_provider.rb, spec/java_buildpack/framework/luna_security_provider_spec.rb
With Java 9, the extension directory functionality was dropped. This means the buildpack has to handle installation different for Java 8 and Java 9+. With Java 8, we add the required files to the extension directory. With Java 9, we add the required JAR file to the classpath, but this was not sufficient to load the required shared library. To fix this, we are adding the Luna API shared library to the LD_LIBRARY_PATH environment variable. The JVM uses this to locate shared libraries, so it can now find the shared library.
=> Add Luna API shared library to library path for Java 9+

config/luna_security_provider.yml
The Luna Security Provider site went down. Thales has provided the binaries and we have relocated them to the standard download repository. This may be temporary, it's not clear at this time, but it will get the buildpack back and working again. It has been broken since the site went down.
=> Switch Luna download URLs

config/components.yml, config/protect_app_security_provider.yml
The ProtectApp download site has gone offline. This PR disables ProtectApp. You can re-enable it if you are able to how your own repository for the downloads.
=> Disable ProtectApp

rakelib/dependency_cache_task.rb
PR #941 introduced a bug in packaging that wasn't caught by unit tests. The removal of this empty block generated a LocalJumpError. This PR adds it back and tells rubocop to ignore the empty block.
=> Fixes package bug introduced in refactoring

lib/java_buildpack/framework/spring_auto_reconfiguration.rb, spec/java_buildpack/framework/spring_auto_reconfiguration_spec.rb
- Add a deprecation warning if you are manually including Spring Cloud Connectors in your app
- Add a deprecation warning if you are relying on Spring Auto Reconfiguration, which has Spring Cloud Connectors shaded into it
- Do not include Spring Auto Reconfiguration if java-cfenv JARs are present in the app
=> Add deprecation warnings around SAR/SCC

lib/java_buildpack/framework/spring_auto_reconfiguration.rb
This new link points directly to a new section in the docs on migrations. The link target doesn't yet exist, but will once documentation updates are published.
=> Update deprecation link

config/components.yml, config/takipi_agent.yml
The download site for the Takipi Agent has gone dark, and attempts to alert the vendor and rectify the situation have failed. This component will no longer be enabled with the default distribution of the Java buildpack. You can re-enable it if you are able to host your own repository for the downloads.
If/when the vendor is able to resolve the situation, we can re-enable the agent by default in the buildpack.
=> Remove Takipi Agent

lib/java_buildpack/jre/ibm_jre_initializer.rb
After refactoring for Ruby 3.0 compatibility, it looks like there's now a missing dependency. This PR adds the missing 'tempfile' require.
Resolves #955 
=> Require missing library

README.md, config/components.yml, config/zing_jre.yml, docs/jre-zing_jre.md, lib/java_buildpack/jre/open_jdk_like.rb, lib/java_buildpack/jre/zing_jre.rb
modified:   README.md
modified:   config/components.yml
new file:   config/zing_jre.yml
new file:   docs/jre-zing_jre.md
new file:   lib/java_buildpack/jre/zing_jre.rb
=> Add Azul Platform Prime to java-buildpack

.idea/runConfigurations/All_Tests__2_5_.xml, .idea/runConfigurations/All_Tests__2_7_.xml, .idea/runConfigurations/All_Tests__3_0_.xml, .idea/runConfigurations/Without_Integration_Tests__2_5_.xml, .idea/runConfigurations/Without_Integration_Tests__2_7_.xml, .idea/runConfigurations/Without_Integration_Tests__3_0_.xml, README.md, config/graal_vm_jre.yml, config/ibm_jre.yml, config/open_jdk_jre.yml, config/oracle_jre.yml, config/packaging.yml, config/sap_machine_jre.yml, config/zulu_jre.yml, java-buildpack.iml, lib/java_buildpack/util/configuration_utils.rb, rakelib/dependency_cache_task.rb, rakelib/package.rb, rakelib/utils.rb, rakelib/versions_task.rb, spec/java_buildpack/util/configuration_utils_spec.rb
1. Adds an environment variable that can be used by operations teams to set default values. Operator defaults override buildpack defaults, but are overridden by application developer values. Operator defaults are set by exposing an environment variable of the pattern `JBP_DEFAULT_<config-file>='<inline-yaml>'`. So to set a default Java version, `JBP_DEFAULT_OPEN_JDK_JRE='{ jre: { version: 11.+ }}'`.
2. Adds `config/packaging.yml`. This contains the list of component data. Each component gets a name, CVE notes link and release notes link. This information is used by the `rake versions` command to generate a nice set of release notes for each package. This information was refactored out of the scripts (was previously hard-coded).
3. Each `config/<jre>.yml` file has been given a …
=> Add default functionality & refactor packaging

config/spring_auto_reconfiguration.yml
As per notices and issue #951, this PR disables Spring Auto Reconfiguration by default.
=> Disables the SAR library by default

config/spring_auto_reconfiguration.yml, lib/java_buildpack/framework/spring_auto_reconfiguration.rb
This re-enables the Spring AutoReconfiguration framework by default, to give users more time to [migrate](https://docs.cloudfoundry.org/buildpacks/java/configuring-service-connections.html#migrating) to `java-cfenv`
=> Re-enables auto-reconfig by default

config/sky_walking_agent.yml
Replace hard-coded https://java-buildpack.cloudfoundry.org/ with {default.repository.root} for Apache SkyWalking Framework
=> Use default.repository.root for Sky Walking Framework

rakelib/package.rb
Fixes #986 by ensuring both sets of binaries are packaged for offline builds
=> Fixed issue with offline packaging for cflinuxfs4/jammy

ci/Dockerfile
Bundler does not work with 2.5.9
=> Dockerfile ruby fix

bin/ruby-run, rakelib/dependency_cache_task.rb
=> Fixes rubocop violations

.rubocop.yml, ci/Dockerfile
I added a 3.1 version to the CI Dockerfile and updated the `.rubocop.yml` to mostly ignore the issue it found with the code. Both offenses were instances of new functionality in 3.1 which we shouldn't upgrade to in order to maintain backwards-compatible support.
=> Adds CI/Rubocop support for Ruby 3.1

config/sap_machine_jre.yml
SapMachine has so only offered one URL for its versions, https://sap.github.io/SapMachine/assets/cf/jre/linux/x86_64/index.yml. We now also differentiate platform types, that is we have https://sap.github.io/SapMachine/assets/cf/jre/bionic/x86_64/index.yml and https://sap.github.io/SapMachine/assets/cf/jre/jammy/x86_64/index.yml from which the deployment should chose.
=> Distinguish platforms in SapMachine repository root URL

bin/run
Updates the check for when to install Ruby, the script now checks for an existing installed Ruby and proceeds if none is found.
=> Update Ruby check for cflinuxfs4 stack

lib/java_buildpack/jre/zing_jre.rb
This fixes the generated start command for Zing JRE apps and the add_preformatted_options error mentioned here: https://github.com/cloudfoundry/java-buildpack/pull/1005
=> fix start command and options error

bin/run
This Buildpack bootstraps Ruby into `/tmp/ruby`, and there are situations where multiple Buildpacks attempt to bootstrap Ruby into the same location.
=> Install bootstrapped Ruby into java-buildpack specific location

config/contrast_security_agent.yml
Updates Contrast Java Agent to version 5.0.
Release notes can be found here: https://docs.contrastsecurity.com/en/java-agent-release-notes-and-archive.html#java-5-0-0
Recommendation is for all customers to update because there is Java 19 support as well as a myriad of bug fixes:
To name a few notable changes
> Language versions currently supported: Java 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19
Kafka Support
Spring Boot 3 Support & Spring 6.
=> Update Contrast Agent Version to 5.0

README.md, docs/framework-azure_application_insights_agent.md, lib/java_buildpack/framework/azure_application_insights_agent.rb, spec/java_buildpack/framework/azure_application_insights_agent_spec.rb
Improvements to Azure Application Insights Agent to make version 3.x usable using a connection string (see also #980). Also added some initial documentation
=> Add connection string for Azure Application Insights Agent 3.x

lib/java_buildpack/framework/azure_application_insights_agent.rb, spec/java_buildpack/framework/azure_application_insights_agent_spec.rb
Fixes unit test to support optional service credentials, and fixes Rubocop issue with long line
=> Polishing for Azure App Insights testing & Rubocop

lib/java_buildpack/util/sanitizer.rb, spec/java_buildpack/util/sanitize_spec.rb
Masking the private part of the API Token
Fix for Issue [#967](https://github.com/cloudfoundry/java-buildpack/issues/967)
=> Handle Dynatrace API Token in the sanitizer

bin/run
If a user specifies a custom stack -- for example, a Paketo stack based on Ubuntu Jammy -- this check will fail and ruby will not be installed, causing the app to fail to stage.
This change skips installing ruby _only_ when the specified stack is cflinuxfs3, which is known to include its own ruby.
I considered a few alternatives before landing on this one:
- Removing the check entirely. It would result in an unnecessary installation of ruby for cflinuxfs3, but I suspect it would work all the same.
- Checking for ruby using `which ruby`, as the code does in line 97. In this case, we may want to move the call to `util::environment::setup` into the `if` block:
```
if ! which ruby > /dev/null; then
mkdir -p "${RUBY_DIR}"
util::install
util::environment::setup
fi
```
I'm open to these other …
=> Install ruby when custom stacks are used

config/app_dynamics_agent.yml
Support was added to [dependency-builder](https://github.com/cloudfoundry/java-buildpack-dependency-builder/pull/42) for AppD agent, this sets the repository root to the default so that the latest agent(s) are installed.
=> Updates repository location for AppD

config/google_stackdriver_debugger.yml
Reverts cloudfoundry/java-buildpack#1021
This change pushes the buildpack over the size limit, and is only temporary since the Debugger agent will not be supported after Aug 23. We will keep the 2.x version and mark the Agent deprecated for removal in a coming release.
=> Revert "Updates Stackdriver Debugger to 3.x line, before deprecation"

config/components.yml, config/packaging.yml
As announced in the previous release, this disables the Google Stackdriver Debugger integration by default, since the Google service is offline and its OSS replacement is temporary and will no longer be supported after the end of Aug 23.
PR also contains updates to release note pages.
=> Disables Google Stackdriver Debugger framework

config/tomcat.yml
Updating geode store default value to 1.14.9 to be more compatible with GemFire 9.15.6.
=> Update geode-store for compatibility with Gemfire 9.15.6

docs/container-dist_zip.md
* add precision over the bin scripts detection
=> Fix documentation

docs/framework-maria_db_jdbc.md, lib/java_buildpack/framework/maria_db_jdbc.rb, spec/java_buildpack/framework/maria_db_jdbc_spec.rb
* Mysql connector was renamed recently from mysql-connector-java to mysql-connector-j, and needs to be detected by the buildpack
* Rephrase documentation to make it more obvious that if a maria db client or mysql connector exist, the buildpack should not add its own mariadb connector
=> Fix #1027: properly detect new mysql connector

lib/java_buildpack/container/tomcat/tomcat_geode_store.rb
Following updates to the geode_store tar files, gemfire artifacts are used instead of geode artifacts. This can create an issue where building a custom buildpack fails due to an internal check that looks for the geode-modules jar. This PR updates the regex for this check to work for either geode or gemfire modules jars.
=> Improved geode_store validation regex to identify gemfire or geode jars

config/contrast_security_agent.yml
Updates Contrast Java Agent to version 6.0.
Release notes can be found here: https://docs.contrastsecurity.com/en/java-agent-release-notes-and-archive.html#java-6-0-0
Recommendation is for all customers to update because there is Java 21 LTS support as well as many bug fixes
=> Update Contrast Agent to 6.0

spec/java_buildpack/framework/open_telemetry_javaagent_spec.rb
Tests expect a bound service to be provided before component release is called
=> Fixes test for otel agent

docs/framework-java-cfenv.md, lib/java_buildpack/framework/java_cf_env.rb, lib/java_buildpack/util/spring_boot_utils.rb, spec/fixtures/framework_java_not_spring_boot3/META-INF/MANIFEST.MF, spec/java_buildpack/framework/java_cfenv_spec.rb
This PR changes the condition that checks when to contribute the Java CFEnv framework for Boot 3 apps. Previously, the condition checks for Spring Boot 3 using either the Manifest entry `Spring-Boot-Version` or presence of `spring-boot-<version>.jar` files.
This change ensures only the presence of the Manifest entry with a version > 3 is used to determine whether the app is a Spring Boot 3 app.
=> Improvement to condition to trigger java-cfenv framework

docs/framework-splunk_otel_java_agent.md
=> Splunk docs polishing

resources/tomcat/conf/server.xml, spec/fixtures/container_tomcat_geode_store/.java-buildpack/tomcat/conf/server.xml, spec/fixtures/container_tomcat_geode_store_server_after.xml
fix for #881
it is a known issue that gorouter -> java applications do not work properly together, once keepalive is used: https://knowledge.broadcom.com/external/article/298104/intermittent-502-eof-gorouter-errors-for.html
The fix is described in the link, but not implemented so far for the java buildpack
=> harmonization of gorouter -> java app communication

docs/framework-dynatrace_one_agent.md, lib/java_buildpack/component/base_component.rb, lib/java_buildpack/framework/dynatrace_one_agent.rb, lib/java_buildpack/util/sanitizer.rb
This adds handling for a new, optional, property named `addtechnologies` a user can configure in a CF service which enables them to add additional OneAgent code-modules to a given java-buildpack deployment.
This is required in multi-buildpack and sidecar scenarious to also monitor other technologies besides java.
Also had to refactor the URL sanitization a bit, because it was eating up multiple `include` parameters which resulted in displaying a faulty log output.
=> Add multi-tech support to Dynatrace OneAgent integration

config/sap_machine_jre.yml
We have moved our web presence to https://sapmachine.io/ so the link needs to be updated. The old URL will still be supported for a while, though.
=> Update link to SapMachine repository
