cloudfoundry/java-buildpack

docs/framework-app_dynamics_agent.md, docs/framework-maria_db_jdbc.md, docs/framework-new_relic_agent.md, docs/framework-postgresql_jdbc.md, docs/framework-spring_insight.md
Updating docs which contain links to the CloudFoundry VCAP_SERVICES doc to the correct URL.
=> update the url link to the VCAP_SERVICES doc

docs/container-tomcat.md
This commit adds documentation about the new support for GemFire based
session replication.
[#87648402]
=> Document the GemFire session replication support

lib/java_buildpack/framework/spring_auto_reconfiguration/web_xml_modifier.rb, spec/fixtures/web_servlet_existing_load_on_startup_after.xml, spec/fixtures/web_servlet_existing_load_on_startup_before.xml, spec/fixtures/web_servlet_load_on_startup_after.xml, spec/fixtures/web_servlet_load_on_startup_before.xml, spec/java_buildpack/framework/spring_auto_reconfiguration/web_xml_modifier_spec.rb
=> web.xml adds servlet init-params before any load-on-startup element

README.md, config/components.yml, docs/framework-checkmarx_iast_agent.md, lib/java_buildpack/framework/checkmarx_iast_agent.rb, spec/java_buildpack/framework/checkmarx_iast_agent_spec.rb
Add support for running apps with the Checkmarx IAST agent, if a checkmarx-iast service is detected
resolves [#821]
=> Checkmarx IAST Framework

rakelib/dependency_cache_task.rb
=> Fix cached JRE for java 15

config/tomcat.yml, docs/container-tomcat.md, lib/java_buildpack/container/tomcat/tomcat_geode_store.rb, spec/fixtures/container_tomcat_geode_store_cache_client_after.xml, spec/fixtures/container_tomcat_geode_store_context_after.xml
- Update version of Geode dependencies being pulled in by the buildpack
- Update version of Tomcat module used by Geode store
- Removed unnecessary client functions added by Geode store
=> Update geode-store version

README.md, rakelib/dependency_cache_task.rb
Polish for #852 
* README updates
* use commas to delimit components instead of colons
Signed-off-by: Emily Casey <ecasey@vmware.com>
=> Polishing ADD_TO_CACHE

config/components.yml, config/sealights_agent.yml, docs/framework-sealights_agent.md, lib/java_buildpack/framework/sealights_agent.rb, rakelib/versions_task.rb, spec/java_buildpack/framework/sealights_agent_spec.rb
=> Implement Sealights Agent framework

Gemfile.lock, docs/framework-app_dynamics_agent.md, docs/framework-luna_security_provider.md, lib/java_buildpack/framework/app_dynamics_agent.rb, lib/java_buildpack/framework/luna_security_provider.rb, lib/java_buildpack/util/external_config.rb, spec/java_buildpack/framework/luna_security_provider_spec.rb
- Extracts external configuration code into a utility
- Modifies AppDynamics to use the utility code
- Modifies Luna Security Provider to use the utility code
- Updates documentation for AppDynamics and Luna to explaini how external configuration works
Resolves: #875
=> Adds external configuration support for Luna Security Module

lib/java_buildpack/util/external_config.rb
This PR will sanitize URLS used to load external configuration (used by App Dynamics framework & Luna framework). This ensures that basic auth creds are not leaked into the logs.
=> Sanitize URLs before logging them

rakelib/versions_task.rb
=> Add release notes link for Azure App Insights

rakelib/versions_task.rb
In preparation for release, bump the release notes links.
=> Bump release notes links for Java & Yourkit

rakelib/versions_task.rb
=> Update release note links

lib/java_buildpack/framework/elastic_apm_agent.rb, spec/java_buildpack/framework/elastic_apm_agent_spec.rb
=> Permit raw type values in Elastic APM config

lib/java_buildpack/jre/zing_jre.rb
=> Fixes Rubocop complaints

README.md
=> Fixes typo in README regarding `JBP_DEFAULT`

docs/framework-sealights_agent.md, lib/java_buildpack/framework/sealights_agent.rb, spec/java_buildpack/framework/sealights_agent_spec.rb
+Explicitly set agent automatic upgrade flag
=> [Sealights Integration] Accept lab_id, proxy and enable_upgrade from user provisioned service

lib/java_buildpack/jre/zing_jre.rb
Fixes Rubocop issue with empty command
=> Fixes rubocop issue with Zing JRE framework

config/azure_application_insights_agent.yml
Upgrade Azure Application Insights Agent major version 2.x to 3.x (see #980)
=> Update default Azure Application Insights Agent version

config/packaging.yml, docs/framework-open_telemetry_javaagent.md
Provides example of user-provided service settings required & additional options link
=> Updates doc and adds packaging entry for new otel framework

.github/workflows/release-reminder.yml
Adds workflow to file release reminder issue every 2nd and 4th Thursday of the month
=> Add release reminder workflow

config/packaging.yml
=> Contrast agent release note update

lib/java_buildpack/framework/maria_db_jdbc.rb
adding aws-mysql-jdbc*.jar to detecting list. Refer to
https://github.com/cloudfoundry/java-buildpack/issues/1067
=> add aws-mysql-jdbc*.jar

config/packaging.yml, config/tomcat.yml, rakelib/dependency_cache_task.rb, rakelib/package.rb, rakelib/utils.rb
Adds support for multiple version lines of Tomcat (similar to JRE lines), as 9 & 10.1 are current stable lines.
=> Adds support for Tomcat 10.1 alongside 9

config/packaging.yml
=> Release Note Updates
